---
### Jeff Geerling :: Dotfiles ###
configure_dotfiles: true

dotfiles_repo: https://github.com/gtb08177/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Developer/.dotfiles_active
dotfiles_files:
  - .zshrc
  - .gitignore
  - .gitconfig
  # - .inputrc
  # - .osx
  # - .vimrc


### Jeff Geerling :: Homebrew ###
homebrew_installed_packages:
  - zsh
  - sqlite
  - gnupg
  - git
  - curl
  - openssl
  - python
  - node
  - terraform
  - httpstat
  - mtr
homebrew_cask_apps:
  - google-chrome
  - iterm2
  - cyberduck
  - postman
  - docker
  - skype
  - spotify
  - visual-studio-code
  - spectacle
  - vagrant
  - 1password
  - etcher
  - istat-menus
  - vlc
  - caffeine
  - whatsapp
  - topnotch
  - mullvadvpn
  - openvpn-connect
  # - get-iplayer-automator
