# TODO : Once SSH keys are in place, pull down a subset of the Github repos?
---
- hosts: localhost
  vars_files:
    - config.yml
  tasks:
    - name: Ensure home/Developer directory exists
      tags: dev
      file:
        path: "/Users/ryan/Developer"
        state: directory

    - name: Ensure SSH config is in place
      tags: ['ssh']
      synchronize:
        src: "./resources/ssh/config"
        dest: "~/.ssh/"
        delete: yes

  #   - name: Configure environment variables
  #     template:
  #       src: "templates/setenv.plist.j2"
  #       dest: "~/Library/LaunchAgents/setenv.{{ item.name }}.plist"
  #     with_items:
  #       - "{{ env_vars }}"
  roles:
    # - role: geerlingguy.homebrew
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles','dev']
